using TradingPlatform.Core.Models;

namespace TradingPlatform.StrategyEngine.Models;

/// <summary>
/// Trading signal request for manual execution
/// </summary>
public record SignalRequest(
    string StrategyId,
    string Symbol,
    SignalType SignalType,
    decimal Price,
    int Quantity,
    string Reason,
    Dictionary<string, object>? Metadata = null);

/// <summary>
/// Strategy execution result
/// </summary>
public record StrategyResult(
    bool Success,
    string Message,
    string? ErrorCode = null,
    Dictionary<string, object>? Data = null);

/// <summary>
/// Trading signal generated by strategy
/// </summary>
public record TradingSignal(
    string Id,
    string StrategyId,
    string Symbol,
    SignalType SignalType,
    decimal Price,
    int Quantity,
    decimal Confidence,
    string Reason,
    DateTimeOffset CreatedAt,
    Dictionary<string, object>? Metadata = null);

/// <summary>
/// Strategy information and status
/// </summary>
public record StrategyInfo(
    string Id,
    string Name,
    StrategyStatus Status,
    DateTimeOffset StartedAt,
    decimal PnL,
    int TradeCount,
    Dictionary<string, object>? Parameters = null);

/// <summary>
/// Strategy performance metrics
/// </summary>
public record StrategyPerformance(
    string StrategyId,
    decimal TotalPnL,
    decimal UnrealizedPnL,
    int TotalTrades,
    int WinningTrades,
    int LosingTrades,
    decimal WinRate,
    decimal SharpeRatio,
    decimal MaxDrawdown,
    TimeSpan ActiveDuration,
    DateTimeOffset LastUpdate);

/// <summary>
/// Strategy execution metrics
/// </summary>
public record ExecutionMetrics(
    long SignalsProcessed,
    TimeSpan AverageExecutionTime,
    TimeSpan MaxExecutionTime,
    int ActiveStrategies,
    long TotalExecutions,
    TimeSpan Uptime,
    DateTimeOffset LastMetricsUpdate);

/// <summary>
/// Strategy engine health status
/// </summary>
public record StrategyHealthStatus(
    bool IsHealthy,
    string Status,
    int ActiveStrategies,
    long RecentSignals,
    TimeSpan AverageLatency,
    DateTime LastExecution,
    string[] Issues);

/// <summary>
/// Market conditions assessment
/// </summary>
public record MarketConditions
{
    public string Symbol { get; init; } = string.Empty;
    public decimal Price { get; init; }
    public decimal Volatility { get; init; }
    public decimal Volume { get; init; }
    public decimal PriceChange { get; init; }
    public TrendDirection Trend { get; init; }
    public decimal RSI { get; init; }
    public decimal MACD { get; init; }
    public decimal MarketBreadth { get; init; }
    public DateTimeOffset Timestamp { get; init; }
    
    // Constructor for backward compatibility
    public MarketConditions(
        string symbol,
        decimal volatility,
        decimal volume,
        decimal priceChange,
        TrendDirection trend,
        decimal rsi,
        decimal macd,
        DateTimeOffset timestamp)
    {
        Symbol = symbol;
        Volatility = volatility;
        Volume = volume;
        PriceChange = priceChange;
        Trend = trend;
        RSI = rsi;
        MACD = macd;
        Timestamp = timestamp;
        Price = 100m; // Default value
        MarketBreadth = 0.5m; // Default value
    }
    
    public MarketConditions() { }
}

/// <summary>
/// Risk assessment for strategy execution
/// </summary>
public record RiskAssessment(
    decimal MaxPositionSize,
    decimal StopLoss,
    decimal TakeProfit,
    decimal RiskReward,
    decimal PortfolioRisk,
    bool IsAcceptable);

// Enums for strategy modeling
public enum SignalType
{
    Buy,
    Sell,
    Hold,
    StopLoss,
    TakeProfit
}

public enum StrategyStatus
{
    Stopped,
    Starting,
    Running,
    Paused,
    Stopping,
    Error
}

public enum TrendDirection
{
    Up,
    Down,
    Sideways,
    Unknown
}

/// <summary>
/// Strategy configuration parameters
/// </summary>
public record StrategyConfig(
    string StrategyId,
    string Name,
    bool IsEnabled,
    Dictionary<string, object> Parameters,
    RiskLimits RiskLimits,
    string[] Symbols);

/// <summary>
/// Risk limits for strategy execution
/// </summary>
public record RiskLimits(
    decimal MaxPositionSize,
    decimal MaxDailyLoss,
    decimal MaxPortfolioRisk,
    int MaxOpenPositions,
    decimal StopLossPercentage);

/// <summary>
/// Strategy manager metrics for service monitoring
/// </summary>
public record StrategyMetrics
{
    public long TotalStrategiesStarted { get; init; }
    public long TotalStrategiesStopped { get; init; }
    public long TotalConfigUpdates { get; init; }
    public int ActiveStrategies { get; init; }
    public int RunningStrategies { get; init; }
    public int PausedStrategies { get; init; }
    public int ConfiguredStrategies { get; init; }
    public DateTime Timestamp { get; init; }
}